## Propuesta de Modelo Gabriel

In [17]:
# Para la manipulación de datos
import pandas as pd
import numpy as np

# Para generar el modelo
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.neighbors import NearestNeighbors, KNeighborsClassifier

# Para guardar el modelo 
import pickle

In [19]:
df=pd.read_csv("total_df.csv")
df=df.drop(columns="Unnamed: 0")
df

,Localidad,Latitud,Longitud,Provincia,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,...,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,rad-media
0,Guadame,36.706119,-4.439046,Málaga,76.72,77.23,122.26,171.33,223.91,229.21,...,205.00,201.59,214.67,235.77,215.11,164.25,121.93,104.42,82.75,154.901310
1,Puebla de Guzman,37.612887,-7.248890,Huelva,70.01,83.17,132.80,185.78,234.91,226.77,...,212.75,219.50,220.50,252.31,227.85,151.33,110.74,88.83,72.76,158.100119
2,Huelva,37.257587,-6.948494,Huelva,70.01,83.17,132.80,185.78,234.91,226.77,...,212.75,219.50,220.50,252.31,227.85,151.33,110.74,88.83,72.76,158.100119
3,Andújar,38.039236,-4.050560,Jaén,64.11,68.83,127.59,164.50,210.55,216.39,...,197.67,197.54,207.33,253.25,234.22,150.33,123.83,91.42,72.42,153.876667
4,Carmona,37.471788,-5.641291,Sevilla,73.31,78.10,133.74,177.53,230.64,224.26,...,204.83,210.03,230.08,258.68,234.22,169.08,119.01,81.83,63.29,156.702083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,Son Servera,39.622273,3.360598,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
538,Santanyi,39.354312,3.129480,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
539,Ciutadella,40.000440,3.835237,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
540,Sant Josep de sa Talaia,38.904361,1.317810,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
541,Sineu,39.643140,3.011611,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750

In [20]:
df['rad-media'].fillna(100.0898789, inplace=True)
df

,Localidad,Latitud,Longitud,Provincia,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,...,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,rad-media
0,Guadame,36.706119,-4.439046,Málaga,76.72,77.23,122.26,171.33,223.91,229.21,...,205.00,201.59,214.67,235.77,215.11,164.25,121.93,104.42,82.75,154.901310
1,Puebla de Guzman,37.612887,-7.248890,Huelva,70.01,83.17,132.80,185.78,234.91,226.77,...,212.75,219.50,220.50,252.31,227.85,151.33,110.74,88.83,72.76,158.100119
2,Huelva,37.257587,-6.948494,Huelva,70.01,83.17,132.80,185.78,234.91,226.77,...,212.75,219.50,220.50,252.31,227.85,151.33,110.74,88.83,72.76,158.100119
3,Andújar,38.039236,-4.050560,Jaén,64.11,68.83,127.59,164.50,210.55,216.39,...,197.67,197.54,207.33,253.25,234.22,150.33,123.83,91.42,72.42,153.876667
4,Carmona,37.471788,-5.641291,Sevilla,73.31,78.10,133.74,177.53,230.64,224.26,...,204.83,210.03,230.08,258.68,234.22,169.08,119.01,81.83,63.29,156.702083
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,Son Servera,39.622273,3.360598,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
538,Santanyi,39.354312,3.129480,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
539,Ciutadella,40.000440,3.835237,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
540,Sant Josep de sa Talaia,38.904361,1.317810,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750
541,Sineu,39.643140,3.011611,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,190.00,177.22,195.83,208.48,198.83,140.33,113.93,79.00,67.86,143.753750

In [4]:
df_suelos=pd.read_excel("Precio_medio_provincias.xlsx")
df_suelos
media_por_provincia = df_suelos.groupby('Lugar')['precio_medio'].mean().reset_index()
media_por_provincia.columns = ['Lugar', 'precio_medio_provincia']

# Fusionar los datos calculados con el DataFrame original
df_suelos = pd.merge(df_suelos, media_por_provincia, on='Lugar')
df_suelos=df_suelos[['Lugar','Anio','precio_medio','precio_medio_provincia']]
df_suelos

FileNotFoundError: [Errno 2] No such file or directory: 'Precio_medio_provincias.xlsx'

In [21]:
ohe=OneHotEncoder()
feature_array=ohe.fit_transform(df[['Provincia', 'rad-media']]).toarray()
labels=ohe.categories_
np.array(labels,dtype='object').ravel()

array([array(['Albacete', 'Alicante', 'Almería', 'Asturias', 'Badajoz',
              'Barcelona', 'Burgos', 'Cantabria', 'Castellón', 'Ciudad Real',
              'Cuenca', 'Cáceres', 'Cádiz', 'Córdoba', 'Galicia', 'Gerona',
              'Gipuzcoa', 'Granada', 'Guadalajara', 'Huelva', 'Huesca',
              'Islas Baleares', 'Jaén', 'La Coruña', 'La Rioja', 'León',
              'Lleida', 'Lugo', 'Lérida', 'Madrid', 'Murcia', 'Málaga',
              'Navarra', 'Orense', 'Palencia', 'Pontevedra', 'Salamanca',
              'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo',
              'Valencia', 'Valladolid', 'Vizcaya', 'Zamora', 'Zaragoza', 'Álava'],
             dtype=object)                                                        ,
       array([ 82.8235119 ,  83.16565476, 100.0898789 , 105.4485119 ,
              108.8475    , 110.31220238, 110.33184524, 113.09464286,
              114.03494048, 115.89303571, 117.58910714, 121.55863095,
              123.01172619, 128.55720238, 129.4302381 , 132.2552381 ,
              133.86095238, 134.84922619, 138.4560119 , 138.67892857,
              141.1977381 , 141.43029762, 141.94535714, 141.95815476,
              142.53845238, 143.33916667, 143.35541667, 143.66053571,
              143.75375   , 144.41827381, 145.0025    , 145.5647619 ,
              147.2564881 , 148.63166667, 150.11803571, 150.30684524,
              150.3752381 , 151.02196429, 151.27214286, 153.87666667,
              154.90130952, 156.51761905, 156.70208333, 157.11446429,
              157.83684524, 158.10011905, 159.67119048])             ],
      dtype=object)

In [22]:
feature_label=np.array(labels,dtype='object').ravel()

In [23]:
labelss = []
for i in feature_label:
    for j in i:
        labelss.append(j)
print(labelss)

['Albacete', 'Alicante', 'Almería', 'Asturias', 'Badajoz', 'Barcelona', 'Burgos', 'Cantabria', 'Castellón', 'Ciudad Real', 'Cuenca', 'Cáceres', 'Cádiz', 'Córdoba', 'Galicia', 'Gerona', 'Gipuzcoa', 'Granada', 'Guadalajara', 'Huelva', 'Huesca', 'Islas Baleares', 'Jaén', 'La Coruña', 'La Rioja', 'León', 'Lleida', 'Lugo', 'Lérida', 'Madrid', 'Murcia', 'Málaga', 'Navarra', 'Orense', 'Palencia', 'Pontevedra', 'Salamanca', 'Segovia', 'Sevilla', 'Soria', 'Tarragona', 'Teruel', 'Toledo', 'Valencia', 'Valladolid', 'Vizcaya', 'Zamora', 'Zaragoza', 'Álava', 82.82351190476187, 83.16565476190473, 100.0898789, 105.44851190476194, 108.84750000000004, 110.3122023809524, 110.33184523809524, 113.09464285714289, 114.03494047619044, 115.8930357142857, 117.58910714285716, 121.55863095238094, 123.0117261904762, 128.5572023809523, 129.43023809523805, 132.25523809523807, 133.86095238095234, 134.84922619047623, 138.4560119047619, 138.6789285714286, 141.19773809523818, 141.43029761904774, 141.94535714285715, 141.95815476190475, 142.53845238095232, 143.33916666666678, 143.3554166666667, 143.6605357142857, 143.75375000000005, 144.41827380952373, 145.0025, 145.56476190476192, 147.25648809523804, 148.63166666666672, 150.11803571428567, 150.3068452380952, 150.37523809523813, 151.02196428571426, 151.27214285714282, 153.87666666666675, 154.90130952380946, 156.51761904761904, 156.70208333333343, 157.11446428571426, 157.83684523809526, 158.10011904761916, 159.67119047619053]

In [24]:
labels_str = [str(x) for x in labelss]
len(labels_str)
type(labels_str[77])

str

In [16]:
features=pd.DataFrame(feature_array,columns=labels_str)

features.to_csv(r'C:\Users\Gabriel Castillo\Desktop\Cosas Gabriel\features.csv', index= False)
features

,Albacete,Alicante,Almería,Asturias,Badajoz,Barcelona,Burgos,Cantabria,Castellón,Ciudad Real,...,151.02196428571426,151.27214285714282,153.87666666666675,154.90130952380946,156.51761904761904,156.70208333333343,157.11446428571426,157.83684523809526,158.10011904761916,159.67119047619053
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
538,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
539,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
540,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
541,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
todo=pd.concat([df, features ], axis = 1)
todo

,Localidad,Latitud,Longitud,Provincia,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,...,151.02196428571426,151.27214285714282,153.87666666666675,154.90130952380946,156.51761904761904,156.70208333333343,157.11446428571426,157.83684523809526,158.10011904761916,159.67119047619053
0,Guadame,36.706119,-4.439046,Málaga,76.72,77.23,122.26,171.33,223.91,229.21,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Puebla de Guzman,37.612887,-7.248890,Huelva,70.01,83.17,132.80,185.78,234.91,226.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,Huelva,37.257587,-6.948494,Huelva,70.01,83.17,132.80,185.78,234.91,226.77,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,Andújar,38.039236,-4.050560,Jaén,64.11,68.83,127.59,164.50,210.55,216.39,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,Carmona,37.471788,-5.641291,Sevilla,73.31,78.10,133.74,177.53,230.64,224.26,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
537,Son Servera,39.622273,3.360598,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
538,Santanyi,39.354312,3.129480,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
539,Ciutadella,40.000440,3.835237,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
540,Sant Josep de sa Talaia,38.904361,1.317810,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
541,Sineu,39.643140,3.011611,Islas Baleares,64.97,80.60,123.75,167.86,213.66,215.22,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
nneighbors = NearestNeighbors(n_neighbors= 52, metric = 'cosine').fit(features)

In [27]:
df.iloc[10]

Localidad       Cartaya
Latitud       37.282911
Longitud      -7.154575
Provincia        Huelva
2010-01           70.01
                ...
2023-09          151.33
2023-10          110.74
2023-11           88.83
2023-12           72.76
rad-media    158.100119
Name: 10, Length: 173, dtype: object

In [28]:
features.iloc[[10]]

,Albacete,Alicante,Almería,Asturias,Badajoz,Barcelona,Burgos,Cantabria,Castellón,Ciudad Real,...,151.02196428571426,151.27214285714282,153.87666666666675,154.90130952380946,156.51761904761904,156.70208333333343,157.11446428571426,157.83684523809526,158.10011904761916,159.67119047619053
10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [29]:
liked=242
recom=250
# Find the indices of nearest neighbors for the liked restaurant
_, ind = nneighbors.kneighbors(features.iloc[[liked]])

# Display the liked location
print('Liked location ')
print('=' * 60)
print(df.iloc[liked, :])

print('\n')

# Display the recommended location
print('Recommended locations ')
print('=' * 60)
recommended_indices = ind[0][0:recom]  # Exclude the liked restaurant itself
recommended_locations = df.iloc[recommended_indices, :]
print(recommended_locations)

Liked location
============================================================
Localidad        Olmedo
Latitud       41.287098
Longitud       -4.68669
Provincia    Valladolid
2010-01           56.27
                ...
2023-09          145.08
2023-10           99.11
2023-11           59.75
2023-12           45.47
rad-media    141.430298
Name: 242, Length: 173, dtype: object


Recommended locations
============================================================
                 Localidad    Latitud  Longitud    Provincia  2010-01  \
236            Tordesillas  41.500851 -5.000530   Valladolid    56.27
230             La Mudarra  41.779395 -4.944033   Valladolid    56.27
231                Zaratan  41.659455 -4.783320   Valladolid    56.27
320                Viloria  41.445392 -4.382741   Valladolid    56.27
410               Simancas  41.590289 -4.826811   Valladolid    56.27
242                 Olmedo  41.287098 -4.686690   Valladolid    56.27
241       Medina del Campo  41.308550 -4.915026   Valladolid    56.27
234             Valladolid  41.652133 -4.728562   Valladolid    56.27
238               Boecillo  41.540681 -4.699379   Valladolid    56.27
368                 Griñon  40.213661 -3.858148       Madrid    61.41
369          Los Pradillos  40.127578 -3.820608       Toledo    58.62
370         Añover de Tajo  39.987738 -3.766055       Toledo    58.62
341               Quintela  42.139476 -8.100245       Orense    46.80
395              Ventillas  38.495932 -4.293880       Madrid    61.41
397            Sanchinarro  40.493189 -3.656402       Madrid    61.41
390              Galapagar  40.577499 -4.003775       Madrid    61.41
391                Daganzo  40.545195 -3.457850       Madrid    61.41
392  Villarejo de Salvanés  40.168358 -3.273876       Madrid    61.41
393            Majadahonda  40.473055 -3.872414       Madrid    61.41
394             Fuencarral  40.426274 -3.700907       Madrid    61.41
388                 Amazan  43.315440 -4.854852     Asturias    41.50
396             Mirasierra  40.490636 -3.716138       Madrid    61.41
401                 Trillo  40.701430 -2.593018  Guadalajara    57.28
400              Hortaleza  40.472549 -3.642552       Madrid    61.41
367               Torrijos  39.981163 -4.280563       Toledo    58.62
366        Valdecaballeros  39.242741 -5.189786      Badajoz    63.51
364                  Parla  40.237395 -3.771890       Madrid    61.41
402              Calamocha  40.919882 -1.299434       Teruel    55.55
372             Madridejos  39.469720 -3.535374       Toledo    58.62
343                 Lobios  41.901747 -8.084014       Orense    46.80
344                  Conso  42.178019 -7.171857       Orense    46.80
345                  Bande  42.031615 -7.974908       Orense    46.80
346     Puebla de Sanabria  42.054621 -6.634209       Zamora    59.47
347                   Lugo  43.039604 -7.456607      Galicia      NaN
348                 Ludrio  43.123990 -7.422646         Lugo    47.44
349       Venta de la Ines  38.556015 -4.434693  Ciudad Real    60.84
350           Villaviciosa  43.481332 -5.433462     Asturias    41.50
351               Alcorcón  40.349300 -3.828429       Madrid    61.41
365             Buenavista  40.767300 -5.611201    Salamanca    58.80
352              Entrevías  40.379045 -3.671757       Madrid    61.41
354                Leganés  40.328194 -3.765270       Madrid    61.41
355             Villaverde  40.351123 -3.699775       Madrid    61.41
356          Arroyomolinos  39.185599 -6.163063      Cáceres    64.20
357              Valdemoro  40.188860 -3.671430       Madrid    61.41
358              Vilaverde  42.546893 -7.549060         Lugo    47.44
359                  Pinto  40.240985 -3.700507       Madrid    61.41
360             Fregacedos  40.290831 -3.848189       Madrid    61.41
361            Fuenlabrada  40.282476 -3.792342       Madrid    61.41
362                 Getafe  40.308181 -3.730268       Madrid    61.41
363           Navalcarnero  40.287717 -4.014299       Madrid    61.41
353               Vallecas  40.386860 -3.659180       Madrid    61.41
387                 Ólvega  41.779562 -1.984363        Soria    55.37

     2010-02  2010-03  2010-04  2010-05  2010-06  ...  2023-04  2023-05  \
236    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
230    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
231    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
320    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
410    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
242    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
241    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
234    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
238    69.22   113.61   173.65   195.91   202.30  ...   198.17   214.07
368    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
369    74.99   128.28   167.63   217.14   213.22  ...   188.92   197.37
370    74.99   128.28   167.63   217.14   213.22  ...   188.92   197.37
341    66.16   109.09   158.40   171.15   189.61  ...   156.58   188.24
395    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
397    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
390    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
391    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
392    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
393    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
394    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
388    65.90    97.49   140.62   141.79   138.83  ...     0.00     0.00
396    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
401    73.65   123.61   167.29   206.52   201.73  ...   198.00   200.04
400    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
367    74.99   128.28   167.63   217.14   213.22  ...   188.92   197.37
366    75.81   118.83   178.25   215.48   221.74  ...   210.50   205.98
364    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
402    76.72   124.63   161.17   188.42   190.19  ...   187.00   175.75
372    74.99   128.28   167.63   217.14   213.22  ...   188.92   197.37
343    66.16   109.09   158.40   171.15   189.61  ...   156.58   188.24
344    66.16   109.09   158.40   171.15   189.61  ...   156.58   188.24
345    66.16   109.09   158.40   171.15   189.61  ...   156.58   188.24
346    74.44   124.83   174.99   205.82   209.49  ...   195.17   208.91
347      NaN      NaN      NaN      NaN      NaN  ...      NaN      NaN
348    62.27   111.31   153.03   158.14   174.62  ...   149.25   175.15
349    77.89   130.88   179.03   215.61   215.42  ...   188.58   189.62
350    65.90    97.49   140.62   141.79   138.83  ...     0.00     0.00
351    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
365    75.37   123.21   174.49   201.01   197.29  ...   192.75   197.97
352    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
354    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
355    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
356    71.91   120.09   174.57   214.18   217.31  ...   197.17   190.39
357    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
358    62.27   111.31   153.03   158.14   174.62  ...   149.25   175.15
359    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
360    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
361    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
362    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
363    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
353    78.02   127.24   171.69   213.52   209.49  ...   189.50   193.41
387    73.05   119.07   155.19   187.11   184.98  ...   176.58   188.50

     2023-06  2023-07  2023-08  2023-09  2023-10  2023-11  2023-12   rad-media
236   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
230   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
231   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
320   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
410   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
242   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
241   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
234   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
238   210.58   247.23   224.84   145.08    99.11    59.75    45.47  141.430298
368   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
369   202.08   244.13   218.55   147.17   101.35    65.42    57.52  144.418274
370   202.08   244.13   218.55   147.17   101.35    65.42    57.52  144.418274
341   178.50   199.26   181.01   117.17    75.86    37.08    26.26  123.011726
395   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
397   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
390   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
391   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
392   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
393   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
394   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
388     0.00     0.00     0.00     0.00     0.00     0.00     0.00   82.823512
396   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
401   194.42   247.14   221.99   131.58   100.06    64.33    57.69  145.002500
400   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
367   202.08   244.13   218.55   147.17   101.35    65.42    57.52  144.418274
366   211.33   254.63   227.16   156.17   110.05    71.67    59.59  150.118036
364   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
402   172.50   227.68   212.61   139.42   106.61    76.33    62.09  141.197738
372   202.08   244.13   218.55   147.17   101.35    65.42    57.52  144.418274
343   178.50   199.26   181.01   117.17    75.86    37.08    26.26  123.011726
344   178.50   199.26   181.01   117.17    75.86    37.08    26.26  123.011726
345   178.50   199.26   181.01   117.17    75.86    37.08    26.26  123.011726
346   203.50   239.99   214.68   141.67    95.41    59.17    40.56  142.538452
347      NaN      NaN      NaN      NaN      NaN      NaN      NaN  100.089879
348   157.75   172.83   155.78   116.33    73.11    40.42    25.06  115.893036
349   201.33   241.28   212.26   151.08   108.59    70.67    58.21  151.272143
350     0.00     0.00     0.00     0.00     0.00     0.00     0.00   82.823512
351   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
365   188.25   244.56   223.80   133.00    90.24    61.50    45.29  143.339167
352   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
354   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
355   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
356   205.67   240.68   215.79   144.83    94.72    61.33    50.38  148.631667
357   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
358   157.75   172.83   155.78   116.33    73.11    40.42    25.06  115.893036
359   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
360   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
361   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
362   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
363   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
353   195.83   238.53   213.81   133.92   101.53    57.50    51.67  147.256488
387   167.58   219.33   203.14   122.25    92.40    54.83    56.06  134.849226

[52 rows x 173 columns]

In [30]:
recommended_locations

,Localidad,Latitud,Longitud,Provincia,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,...,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,rad-media
236,Tordesillas,41.500851,-5.000530,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
230,La Mudarra,41.779395,-4.944033,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
231,Zaratan,41.659455,-4.783320,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
320,Viloria,41.445392,-4.382741,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
410,Simancas,41.590289,-4.826811,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
242,Olmedo,41.287098,-4.686690,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
241,Medina del Campo,41.308550,-4.915026,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
234,Valladolid,41.652133,-4.728562,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
238,Boecillo,41.540681,-4.699379,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
368,Griñon,40.213661,-3.858148,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
369,Los Pradillos,40.127578,-3.820608,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
370,Añover de Tajo,39.987738,-3.766055,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
341,Quintela,42.139476,-8.100245,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
395,Ventillas,38.495932,-4.293880,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
397,Sanchinarro,40.493189,-3.656402,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
390,Galapagar,40.577499,-4.003775,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
391,Daganzo,40.545195,-3.457850,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
392,Villarejo de Salvanés,40.168358,-3.273876,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
393,Majadahonda,40.473055,-3.872414,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
394,Fuencarral,40.426274,-3.700907,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
388,Amazan,43.315440,-4.854852,Asturias,41.50,65.90,97.49,140.62,141.79,138.83,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,82.823512
396,Mirasierra,40.490636,-3.716138,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
401,Trillo,40.701430,-2.593018,Guadalajara,57.28,73.65,123.61,167.29,206.52,201.73,...,198.00,200.04,194.42,247.14,221.99,131.58,100.06,64.33,57.69,145.002500
400,Hortaleza,40.472549,-3.642552,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
367,Torrijos,39.981163,-4.280563,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
366,Valdecaballeros,39.242741,-5.189786,Badajoz,63.51,75.81,118.83,178.25,215.48,221.74,...,210.50,205.98,211.33,254.63,227.16,156.17,110.05,71.67,59.59,150.118036
364,Parla,40.237395,-3.771890,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
402,Calamocha,40.919882,-1.299434,Teruel,55.55,76.72,124.63,161.17,188.42,190.19,...,187.00,175.75,172.50,227.68,212.61,139.42,106.61,76.33,62.09,141.197738
372,Madridejos,39.469720,-3.535374,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
343,Lobios,41.901747,-8.084014,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
344,Conso,42.178019,-7.171857,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
345,Bande,42.031615,-7.974908,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
346,Puebla de Sanabria,42.054621,-6.634209,Zamora,59.47,74.44,124.83,174.99,205.82,209.49,...,195.17,208.91,203.50,239.99,214.68,141.67,95.41,59.17,40.56,142.538452
347,Lugo,43.039604,-7.456607,Galicia,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.089879
348,Ludrio,43.123990,-7.422646,Lugo,47.44,62.27,111.31,153.03,158.14,174.62,...,149.25,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036
349,Venta de la Ines,38.556015,-4.434693,Ciudad Real,60.84,77.89,130.88,179.03,215.61,215.42,...,188.58,189.62,201.33,241.28,212.26,151.08,108.59,70.67,58.21,151.272143
350,Villaviciosa,43.481332,-5.433462,Asturias,41.50,65.90,97.49,140.62,141.79,138.83,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,82.823512
351,Alcorcón,40.349300,-3.828429,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
365,Buenavista,40.767300,-5.611201,Salamanca,58.80,75.37,123.21,174.49,201.01,197.29,...,192.75,197.97,188.25,244.56,223.80,133.00,90.24,61.50,45.29,143.339167
352,Entrevías,40.379045,-3.671757,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
354,Leganés,40.328194,-3.765270,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
355,Villaverde,40.351123,-3.699775,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
356,Arroyomolinos,39.185599,-6.163063,Cáceres,64.20,71.91,120.09,174.57,214.18,217.31,...,197.17,190.39,205.67,240.68,215.79,144.83,94.72,61.33,50.38,148.631667
357,Valdemoro,40.188860,-3.671430,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
358,Vilaverde,42.546893,-7.549060,Lugo,47.44,62.27,111.31,153.03,158.14,174.62,...,149.25,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036
359,Pinto,40.240985,-3.700507,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
360,Fregacedos,40.290831,-3.848189,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
361,Fuenlabrada,40.282476,-3.792342,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
362,Getafe,40.308181,-3.730268,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
363,Navalcarnero,40.287717,-4.014299,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
353,Vallecas,40.386860,-3.659180,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
387,Ólvega,41.779562,-1.984363,Soria,55.37,73.05,119.07,155.19,187.11,184.98,...,176.58,188.50,167.58,219.33,203.14,122.25,92.40,54.83,56.06,134.849226

In [118]:
presupuesto = 10000000  # 10 millones de euros

# Filtrar ubicaciones recomendadas dentro del presupuesto
filtered_locations = recommended_locations[recommended_locations['precio_medio_provincia'] <= presupuesto]

# Calcular la energía producida por metro cuadrado
filtered_locations['energia_por_metro_cuadrado'] = filtered_locations['rad-media'] * filtered_locations['area']

# Seleccionar la ubicación que produce la mayor energía dentro del presupuesto
ubicacion_optima = filtered_locations.loc[filtered_locations['energia_por_metro_cuadrado'].idxmax()]

print(ubicacion_optima)

KeyError: 'precio_medio_provincia'

In [146]:
recommended_locations

,Localidad,Latitud,Longitud,Provincia,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,...,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,rad-media
236,Tordesillas,41.500851,-5.000530,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
230,La Mudarra,41.779395,-4.944033,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
231,Zaratan,41.659455,-4.783320,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
320,Viloria,41.445392,-4.382741,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
410,Simancas,41.590289,-4.826811,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
242,Olmedo,41.287098,-4.686690,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
241,Medina del Campo,41.308550,-4.915026,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
234,Valladolid,41.652133,-4.728562,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
238,Boecillo,41.540681,-4.699379,Valladolid,56.27,69.22,113.61,173.65,195.91,202.30,...,198.17,214.07,210.58,247.23,224.84,145.08,99.11,59.75,45.47,141.430298
368,Griñon,40.213661,-3.858148,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
369,Los Pradillos,40.127578,-3.820608,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
370,Añover de Tajo,39.987738,-3.766055,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
341,Quintela,42.139476,-8.100245,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
395,Ventillas,38.495932,-4.293880,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
397,Sanchinarro,40.493189,-3.656402,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
390,Galapagar,40.577499,-4.003775,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
391,Daganzo,40.545195,-3.457850,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
392,Villarejo de Salvanés,40.168358,-3.273876,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
393,Majadahonda,40.473055,-3.872414,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
394,Fuencarral,40.426274,-3.700907,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
388,Amazan,43.315440,-4.854852,Asturias,41.50,65.90,97.49,140.62,141.79,138.83,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,82.823512
396,Mirasierra,40.490636,-3.716138,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
401,Trillo,40.701430,-2.593018,Guadalajara,57.28,73.65,123.61,167.29,206.52,201.73,...,198.00,200.04,194.42,247.14,221.99,131.58,100.06,64.33,57.69,145.002500
400,Hortaleza,40.472549,-3.642552,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
367,Torrijos,39.981163,-4.280563,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
366,Valdecaballeros,39.242741,-5.189786,Badajoz,63.51,75.81,118.83,178.25,215.48,221.74,...,210.50,205.98,211.33,254.63,227.16,156.17,110.05,71.67,59.59,150.118036
364,Parla,40.237395,-3.771890,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
402,Calamocha,40.919882,-1.299434,Teruel,55.55,76.72,124.63,161.17,188.42,190.19,...,187.00,175.75,172.50,227.68,212.61,139.42,106.61,76.33,62.09,141.197738
372,Madridejos,39.469720,-3.535374,Toledo,58.62,74.99,128.28,167.63,217.14,213.22,...,188.92,197.37,202.08,244.13,218.55,147.17,101.35,65.42,57.52,144.418274
343,Lobios,41.901747,-8.084014,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
344,Conso,42.178019,-7.171857,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
345,Bande,42.031615,-7.974908,Orense,46.80,66.16,109.09,158.40,171.15,189.61,...,156.58,188.24,178.50,199.26,181.01,117.17,75.86,37.08,26.26,123.011726
346,Puebla de Sanabria,42.054621,-6.634209,Zamora,59.47,74.44,124.83,174.99,205.82,209.49,...,195.17,208.91,203.50,239.99,214.68,141.67,95.41,59.17,40.56,142.538452
347,Lugo,43.039604,-7.456607,Galicia,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.000000
348,Ludrio,43.123990,-7.422646,Lugo,47.44,62.27,111.31,153.03,158.14,174.62,...,149.25,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036
349,Venta de la Ines,38.556015,-4.434693,Ciudad Real,60.84,77.89,130.88,179.03,215.61,215.42,...,188.58,189.62,201.33,241.28,212.26,151.08,108.59,70.67,58.21,151.272143
350,Villaviciosa,43.481332,-5.433462,Asturias,41.50,65.90,97.49,140.62,141.79,138.83,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,82.823512
351,Alcorcón,40.349300,-3.828429,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
365,Buenavista,40.767300,-5.611201,Salamanca,58.80,75.37,123.21,174.49,201.01,197.29,...,192.75,197.97,188.25,244.56,223.80,133.00,90.24,61.50,45.29,143.339167
352,Entrevías,40.379045,-3.671757,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
354,Leganés,40.328194,-3.765270,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
355,Villaverde,40.351123,-3.699775,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
356,Arroyomolinos,39.185599,-6.163063,Cáceres,64.20,71.91,120.09,174.57,214.18,217.31,...,197.17,190.39,205.67,240.68,215.79,144.83,94.72,61.33,50.38,148.631667
357,Valdemoro,40.188860,-3.671430,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
358,Vilaverde,42.546893,-7.549060,Lugo,47.44,62.27,111.31,153.03,158.14,174.62,...,149.25,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036
359,Pinto,40.240985,-3.700507,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
360,Fregacedos,40.290831,-3.848189,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
361,Fuenlabrada,40.282476,-3.792342,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
362,Getafe,40.308181,-3.730268,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
363,Navalcarnero,40.287717,-4.014299,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
353,Vallecas,40.386860,-3.659180,Madrid,61.41,78.02,127.24,171.69,213.52,209.49,...,189.50,193.41,195.83,238.53,213.81,133.92,101.53,57.50,51.67,147.256488
387,Ólvega,41.779562,-1.984363,Soria,55.37,73.05,119.07,155.19,187.11,184.98,...,176.58,188.50,167.58,219.33,203.14,122.25,92.40,54.83,56.06,134.849226

In [16]:
df_suelos.rename(columns={'Lugar': 'Provincia'}, inplace=True)
df_suelos

NameError: name 'df_suelos' is not defined

In [160]:
extension=20000
presupuesto=40000000

# Calcular el costo total de adquirir la tierra para cada ubicación
df_suelos['costo_total'] = df_suelos['precio_medio_provincia'] * extension

# Filtrar ubicaciones dentro del presupuesto
ubicaciones_en_presupuesto = df_suelos[df_suelos['costo_total'] <= presupuesto]
concatenado = pd.merge(ubicaciones_en_presupuesto, recommended_locations, on='Provincia',how="inner")

# Calcular la producción de energía por metro cuadrado para cada ubicación en el presupuesto
concatenado['produccion_energia_por_metro_cuadrado'] = concatenado['rad-media'] * extension

# Seleccionar la ubicación con el mayor rendimiento de radiación dentro del presupuesto
ubicacion_optima = concatenado.loc[concatenado['produccion_energia_por_metro_cuadrado'].idxmax()]

ubicacion_optima

Provincia                                   Ciudad Real
Anio                                               2004
precio_medio                                  96.294395
precio_medio_provincia                        122.81376
costo_total                              2456275.197861
                                              ...
2023-10                                          108.59
2023-11                                           70.67
2023-12                                           58.21
rad-media                                    151.272143
produccion_energia_por_metro_cuadrado    3025442.857143
Name: 260, Length: 178, dtype: object

In [155]:
concatenado

,Provincia,Anio,precio_medio,precio_medio_provincia,costo_total,Localidad,Latitud,Longitud,2010-01,2010-02,...,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,rad-media,produccion_energia_por_metro_cuadrado
0,Teruel,2004,58.681220,74.754557,1.495091e+06,Calamocha,40.919882,-1.299434,55.55,76.72,...,175.75,172.50,227.68,212.61,139.42,106.61,76.33,62.09,141.197738,2.823955e+06
1,Teruel,2005,80.831803,74.754557,1.495091e+06,Calamocha,40.919882,-1.299434,55.55,76.72,...,175.75,172.50,227.68,212.61,139.42,106.61,76.33,62.09,141.197738,2.823955e+06
2,Teruel,2006,99.363190,74.754557,1.495091e+06,Calamocha,40.919882,-1.299434,55.55,76.72,...,175.75,172.50,227.68,212.61,139.42,106.61,76.33,62.09,141.197738,2.823955e+06
3,Teruel,2007,101.286622,74.754557,1.495091e+06,Calamocha,40.919882,-1.299434,55.55,76.72,...,175.75,172.50,227.68,212.61,139.42,106.61,76.33,62.09,141.197738,2.823955e+06
4,Teruel,2008,94.118317,74.754557,1.495091e+06,Calamocha,40.919882,-1.299434,55.55,76.72,...,175.75,172.50,227.68,212.61,139.42,106.61,76.33,62.09,141.197738,2.823955e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
455,Lugo,2021,92.048848,92.165036,1.843301e+06,Vilaverde,42.546893,-7.549060,47.44,62.27,...,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036,2.317861e+06
456,Lugo,2022,58.975572,92.165036,1.843301e+06,Ludrio,43.123990,-7.422646,47.44,62.27,...,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036,2.317861e+06
457,Lugo,2022,58.975572,92.165036,1.843301e+06,Vilaverde,42.546893,-7.549060,47.44,62.27,...,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036,2.317861e+06
458,Lugo,2023,73.442959,92.165036,1.843301e+06,Ludrio,43.123990,-7.422646,47.44,62.27,...,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036,2.317861e+06
459,Lugo,2023,73.442959,92.165036,1.843301e+06,Vilaverde,42.546893,-7.549060,47.44,62.27,...,175.15,157.75,172.83,155.78,116.33,73.11,40.42,25.06,115.893036,2.317861e+06

In [142]:
ubicaciones_en_presupuesto

       Lugar  Anio  precio_medio  precio_medio_provincia   costo_total
0    Almería  2004    326.039472              221.614041  4.432281e+06
1    Almería  2005    510.521821              221.614041  4.432281e+06
2    Almería  2006    360.942906              221.614041  4.432281e+06
3    Almería  2007    346.528446              221.614041  4.432281e+06
4    Almería  2008    298.810774              221.614041  4.432281e+06
..       ...   ...           ...                     ...           ...
855  Vizcaya  2019    243.305167              269.753690  5.395074e+06
856  Vizcaya  2020    248.984359              269.753690  5.395074e+06
857  Vizcaya  2021    226.356173              269.753690  5.395074e+06
858  Vizcaya  2022    229.085316              269.753690  5.395074e+06
859  Vizcaya  2023    280.896948              269.753690  5.395074e+06

[860 rows x 5 columns]

In [33]:
filename = 'Modelo_Radiacion'
pickle.dump(nneighbors, open(filename, 'wb'))